server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**,/staff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9191/eureka



# Okta configuration for API Gateway in microservices
okta:
  oauth2:
    issuer: https://dev-64448348.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaaj1sp70lRBVu3m5d7
    client-secret: gkKc7P3nQR19ysNhYq4AJ7ddbLN4F5zNGy6-2lB8WLrlZiKsw98Zt_A7tV90IM8E
    scopes: openid, profile, email, offline_access

